archivo = open ("texto.file", "r")
texto_ini = archivo.read()
archivo = open("texto.file", "w")
archivo.close()
texto = input("Escribe el texto que quieres poner : ")
archivo.open("texto.file", "w")
archivo.write(texto_ini)
archivo.write("\n")
archivo.write(texto)
archivo.close()